services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/autoservice"
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DEBUG: true
  database:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "14320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: autoservice
  nginx:
    build:
      dockerfile: nginx.Dockerfile
    container_name: autoservice_gateway
    ports:
      - "80:80"
    depends_on:
      - backend
